### ISSUE TITLE
MVP feature checklist

### ISSUE THREAD

**Issue by nhanb** [nhanb/caophim#1]
- [x] Preprocess post content:
  + [x] Write simple parser to spit out a syntax tree: just do line break, paragraphs, greentext (>) and quoted links (>>) for now.
  + [x] Store syntax tree in db, also somehow model the "this post is quoted by posts x, y, z" relationship.
- [x] Store thumbnails
- [x] Support s3/wasabi as alternative storage backend
- [x] Javascript to maximize pics in place
- [ ] Better form UX (on error, show same page with error message instead of separate plaintext error page)
- [x] Mobile friendly UI
- [ ] CI
  + [ ] Release binaries on tagged commits
  + [ ] Deployment
- [ ] i18n
